version: "3.8"
services:
  web:
    build: .
    image: abhisheknaik1112/vozrecx:latest
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
